<b>HTS Legal Information</b><br />

In any site as large as ours that deals with so many controversial topics and skills, it has become necessary to address a few incidents and implement a user terms and services agreement. We want to provide a free, safe and legal training environment to the public, but we can only do so if members of the community do not put us in legal risk.<br /><br />

<i>What's this about federal investigations?</i><br />
It's true. Key organizer Jeremy Hammond(Xec96) among several other HTS users have been questioned by FBI agents as a result of being involved in the Hack This Site community, political activist groups, and having presences at large hacker conventions such as DEFCON or HOPE. This does NOT mean that being associated with Hack This Site, participating in the debates, practicing your skills or knowing these people mean that you should expect visitors in black suits. But this DOES mean that they are watching, and that you need to be very careful what you say and what you do. However, this should NOT hold you back from doing the things you want to do with your life. You just need to play it smart. It is <i>strongly</i> recommended that you read up on and practice good security culture(<a href="http://security.resist.ca/">and here's a great place to start</a>).<br /><br /><br />

<b>Your usage of this website constitutes your agreement to the following terms.</b>
<ol>
        <li>Users are responsible for any content they put on Hack This Site, whether it be in the form of articles, external resources, discussion board entries, user profiles, etc. Hack This Site cannot be held liable for user-submitted posts. Please do not post illegal material (child pornography, credit cards, pirated software, etc).</li>
        <li>Hack This Site does not encourage, condone, or orchestrate attempts to hack into other servers or any other illegal activities. The writings contained inside this website are entertainment / educational purposes only, and what actions people decide to take outside of this website are strictly independent of Hack This Site. We are not responsible if you break the law using techniques listed on this website.</li>
        <li>These challenges are provided to users so that they may learn how to protect their own websites with similar vulnerabilities learned from the challenges on this website.</li>
        <li>You are hereby freely allowed to explore the security of Hack This Site, inside and outside of the challenges. However, you are not permitted to exploit such security holes in a destructive manner (being defined as inhibiting others from using the website in it's entirety, the theft of user personal information, launching attacks on other servers from this website, etc).</li>
        <li>Hack This Site has the sole discretion to remove/edit users, articles, external resources, or any other user-submitted content to protect itself from legal harm. This legal disclaimer may be modified at any time without notice.</li>
</ol>
